# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# This file is committed to source control for convenience.
# To regenerate: protoc --python_out=hive_zero_core/utils protos/swarm.proto
# source: swarm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'swarm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bswarm.proto\"Q\n\x0fKnowledgeUpdate\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x11\n\tembedding\x18\x02 \x01(\x0c\x12\x18\n\x10\x64iscovered_nodes\x18\x03 \x03(\t\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\"$\n\x0cStateRequest\x12\x14\n\x0crequester_id\x18\x01 \x01(\t\"C\n\x0bGlobalState\x12\x1c\n\x14\x61ggregated_embedding\x18\x01 \x01(\x0c\x12\x16\n\x0e\x61\x63tive_experts\x18\x02 \x01(\x05\x32\x66\n\x0cSwarmService\x12*\n\x0eShareKnowledge\x12\x10.KnowledgeUpdate\x1a\x04.Ack\"\x00\x12*\n\tSyncState\x12\r.StateRequest\x1a\x0c.GlobalState\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swarm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KNOWLEDGEUPDATE']._serialized_start=15
  _globals['_KNOWLEDGEUPDATE']._serialized_end=96
  _globals['_ACK']._serialized_start=98
  _globals['_ACK']._serialized_end=120
  _globals['_STATEREQUEST']._serialized_start=122
  _globals['_STATEREQUEST']._serialized_end=158
  _globals['_GLOBALSTATE']._serialized_start=160
  _globals['_GLOBALSTATE']._serialized_end=227
  _globals['_SWARMSERVICE']._serialized_start=229
  _globals['_SWARMSERVICE']._serialized_end=331
# @@protoc_insertion_point(module_scope)
