# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import swarm_pb2 as swarm__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in swarm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SwarmServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShareKnowledge = channel.unary_unary(
                '/SwarmService/ShareKnowledge',
                request_serializer=swarm__pb2.KnowledgeUpdate.SerializeToString,
                response_deserializer=swarm__pb2.Ack.FromString,
                _registered_method=True)
        self.SyncState = channel.unary_unary(
                '/SwarmService/SyncState',
                request_serializer=swarm__pb2.StateRequest.SerializeToString,
                response_deserializer=swarm__pb2.GlobalState.FromString,
                _registered_method=True)


class SwarmServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ShareKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SwarmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShareKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareKnowledge,
                    request_deserializer=swarm__pb2.KnowledgeUpdate.FromString,
                    response_serializer=swarm__pb2.Ack.SerializeToString,
            ),
            'SyncState': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncState,
                    request_deserializer=swarm__pb2.StateRequest.FromString,
                    response_serializer=swarm__pb2.GlobalState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SwarmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SwarmService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SwarmService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ShareKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SwarmService/ShareKnowledge',
            swarm__pb2.KnowledgeUpdate.SerializeToString,
            swarm__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SwarmService/SyncState',
            swarm__pb2.StateRequest.SerializeToString,
            swarm__pb2.GlobalState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
